T3E::window Class Reference
T3E::window Class Reference
Public Member Functions
int create (std::string windowName, int screenWidth, int screenHeight, unsigned int currentFlag)
void destroy ()
void swapBuffer ()
void updateSizeInfo ()
int getScreenWidth ()
int getScreenHeight ()
Detailed Description
Definition at line 21 of file window.h.
Member Function Documentation
int T3E::window::create (std::string windowName, int screenWidth, int screenHeight, unsigned int currentFlag)
Create a window Note: on android the dimensions will be overwritten to fit the full screen size
Parameters
[in] name of the window (e.g. the one displayed in the toolbar on pc)
[in] width of the window in pixels
[in] height of the window in pixels
[in] SDL flags for window options (e.g BORDERLESES, FULLSCREEN, ...)
Definition at line 26 of file window.cpp.
void T3E::window::destroy ()
Free the context and the SDL_window member
Definition at line 9 of file window.cpp.
int T3E::window::getScreenWidth () inline
Getters for window size
Definition at line 65 of file window.h.
Referenced by Credits::run(), and StartMenu::run().
void T3E::window::swapBuffer ()
Swap the current buffer with the other one to display its content on screen (double buffering)
Definition at line 74 of file window.cpp.
Referenced by Credits::run(), and StartMenu::run().
void T3E::window::updateSizeInfo ()
load the actual current window dimensions in the screenWidth_ and screenHeight_ members -use this at least once before using getters for the dimensions of the window -use this again if the window size changes (e.g. on a phone, landscape to normal layout switch)
Definition at line 79 of file window.cpp.
Referenced by Credits::run(), and StartMenu::run().
The documentation for this class was generated from the following files:
Type3Engine/window.h
Type3Engine/window.cpp