T3E::TextRenderer Class Reference
T3E::TextRenderer Class Reference
Public Member Functions
void init ()
void setScreenSize (int width, int height)
void putNumber (int num, unsigned padding, float x, float y, unsigned size_pixels, float alpha=1.0f)
void putString (std::string str, float x, float y, unsigned int size_pixels, float alpha=1.0f)
void putChar (unsigned char c, float x, float y, unsigned int size_pixels, float alpha=1.0f)
void render ()
Detailed Description
Definition at line 10 of file TextRenderer.h.
Member Function Documentation
void T3E::TextRenderer::init ()
Get the font texture and compile shaders
Definition at line 22 of file TextRenderer.cpp.
References T3E::ResourceManager::getTexture(), and T3E::IOManager::readTextToBuffer().
Referenced by Credits::run(), and StartMenu::run().
void T3E::TextRenderer::putChar (unsigned char c, float x, float y, unsigned int size_pixels, float alpha = 1.0f)
Add a single character to be rendered
Parameters
[in] the char to be rendered
[in] x coordinate of the top left corner of the text. -1 -1 is the bottom left of the screen, 1 1 is the top right
[in] y coordinate of the top left corner of the text. -1 -1 is the bottom left of the screen, 1 1 is the top right
[in] the number of pixels wide/tall each character is
Definition at line 179 of file TextRenderer.cpp.
Referenced by setScreenSize().
void T3E::TextRenderer::putNumber (int num, unsigned padding, float x, float y, unsigned size_pixels, float alpha = 1.0f)
Add a number to be rendered
Parameters
[in] the number to be rendered
[in] the amount of space to write the number into
[in] x coordinate of the top left corner of the text. -1 -1 is the bottom left of the screen, 1 1 is the top right
[in] y coordinate of the top left corner of the text. -1 -1 is the bottom left of the screen, 1 1 is the top right
[in] the number of pixels wide/tall each character is
Definition at line 133 of file TextRenderer.cpp.
Referenced by setScreenSize().
void T3E::TextRenderer::putString (std::string str, float x, float y, unsigned int size_pixels, float alpha = 1.0f)
Add a string of characters to be rendered
Parameters
[in] the string to be rendered
[in] x coordinate of the top left corner of the text. -1 -1 is the bottom left of the screen, 1 1 is the top right
[in] y coordinate of the top left corner of the text. -1 -1 is the bottom left of the screen, 1 1 is the top right
[in] the number of pixels wide/tall each character is
Definition at line 159 of file TextRenderer.cpp.
Referenced by Credits::run(), StartMenu::run(), and setScreenSize().
void T3E::TextRenderer::render ()
Render the loaded text and unload it
The text to be rendered must be loaded again after calling this function
Definition at line 197 of file TextRenderer.cpp.
Referenced by Credits::run(), StartMenu::run(), and setScreenSize().
void T3E::TextRenderer::setScreenSize (int width, int height) inline
Set the screen dimension for appropriate rendering
Parameters
[in] width of the screen (pixel resolution)
[in] height of the screen (pixel resolution)
Definition at line 31 of file TextRenderer.h.
References putChar(), putNumber(), putString(), and render().
Referenced by Credits::run(), and StartMenu::run().
The documentation for this class was generated from the following files:
Type3Engine/TextRenderer.h
Type3Engine/TextRenderer.cpp