T3E::IOManager Class Reference
T3E::IOManager Class Reference
Static Public Member Functions
static bool readBinaryToBuffer (std::string filePath, std::vector< unsigned char > &buffer)
static bool readTextToBuffer (std::string filePath, std::vector< char > &buffer)
Detailed Description
Definition at line 11 of file IOManager.h.
Member Function Documentation
bool T3E::IOManager::readBinaryToBuffer (std::string filePath, std::vector< unsigned char > & buffer) static
Reads the Binary from the file to a buffer
Parameters
[in] The string containing the file path that is going to be accessed
[in] The unsigned character buffer that the binary is going to be written into
Definition at line 5 of file IOManager.cpp.
Referenced by T3E::ImageLoader::loadPNG().
bool T3E::IOManager::readTextToBuffer (std::string filePath, std::vector< char > & buffer) static
Reads the text from the file to a buffer
Parameters
[in] The string containing the file path that is going to be accessed
[in] The character buffer that the text is going to be written into
Definition at line 25 of file IOManager.cpp.
Referenced by T3E::GLSLProgram::addAttribute(), T3E::TextRenderer::init(), and T3E::ConfigFile::load().
The documentation for this class was generated from the following files:
Type3Engine/IOManager.h
Type3Engine/IOManager.cpp