StartMenu Class Reference
StartMenu Class Reference
Public Member Functions
command run (T3E::window *window, T3E::AudioEngine *audioEngine)
Detailed Description
Definition at line 33 of file StartMenu.h.
Member Function Documentation
command StartMenu::run (T3E::window * window, T3E::AudioEngine * audioEngine)
Parameters
[in] Window* The window to render to
[in] AudioEngine* The audio engine to use Run handles initialisation of the state then enters the game loop
Definition at line 3 of file StartMenu.cpp.
References T3E::GLSLProgram::addAttribute(), T3E::GLSLProgram::compileShaders(), T3E::Sprite::draw(), T3E::Button::draw(), T3E::window::getScreenWidth(), T3E::ResourceManager::getTexture(), T3E::TextRenderer::init(), T3E::Button::init(), T3E::Sprite::init(), T3E::GLSLProgram::linkShaders(), T3E::AudioEngine::loadSoundEffect(), T3E::Button::press(), T3E::TextRenderer::putString(), T3E::TextRenderer::render(), T3E::TextRenderer::setScreenSize(), T3E::GLSLProgram::stopUse(), T3E::window::swapBuffer(), T3E::Button::touchCollides(), T3E::Button::unpress(), T3E::window::updateSizeInfo(), and T3E::GLSLProgram::use().
The documentation for this class was generated from the following files:
StartMenu.h
StartMenu.cpp