T3E::Button Class Reference
T3E::Button Class Reference
Public Member Functions
void init (float posX, float posY, float width, float height, std::string texturePath, float tileWidth, float tileHeight, float unpressedX, float unpressedY, float pressedX, float pressedY)
bool touchCollides (glm::vec2 touchPos)
void draw ()
void press ()
void unpress ()
void toggle ()
bool isPressed ()
GLuint getTexUnit ()
Detailed Description
Definition at line 10 of file Button.h.
Member Function Documentation
void T3E::Button::draw ()
draws the pressed or unpressed sprite depending on it's condition
Definition at line 30 of file Button.cpp.
References T3E::Sprite::draw().
Referenced by Credits::run(), and StartMenu::run().
GLuint T3E::Button::getTexUnit () inline
Gets the texture unit of the pressed sprite
Returns
the GLuint containing the texture unit of the pressed sprite
Definition at line 81 of file Button.h.
void T3E::Button::init (float posX, float posY, float width, float height, std::string texturePath, float tileWidth, float tileHeight, float unpressedX, float unpressedY, float pressedX, float pressedY)
Initialise the button
Parameters
[in] the x position of the button on the screen
[in] the y position of the button on the screen
[in] the width of the button sprite
[in] the height of the button sprite
[in] texture file path
[in] width of a sprite on the spritesheet
[in] height of a sprite on the spritesheet
[in] the UV x position of the unpressed sprite on the spritesheet
[in] the UV y position of the unpressed sprite on the spritesheet
[in] the UV x position of the pressed sprite on the spritesheet
[in] the UV y position of the pressed sprite on the spritesheet
Definition at line 5 of file Button.cpp.
References T3E::Sprite::init().
Referenced by Credits::run(), and StartMenu::run().
bool T3E::Button::isPressed () inline
checks to see if the button is pressed or not
Returns
[out] the true or false value of if the button has been pressed or not
Definition at line 74 of file Button.h.
void T3E::Button::press () inline
sets the button as being pressed
Definition at line 56 of file Button.h.
Referenced by Credits::run(), and StartMenu::run().
void T3E::Button::toggle () inline
toggles whether or not the button has been pressed or not
Definition at line 66 of file Button.h.
bool T3E::Button::touchCollides (glm::vec2 touchPos)
checks to see if the button has been pressed by the player
Parameters
[in] touch position in screen coordinates
Returns
[out] return true if the coordinates lie inside the sprite, false if they do not
Definition at line 15 of file Button.cpp.
References T3E::Sprite::getPos().
Referenced by Credits::run(), and StartMenu::run().
void T3E::Button::unpress () inline
sets the button as not being pressed
Definition at line 61 of file Button.h.
Referenced by Credits::run(), and StartMenu::run().
The documentation for this class was generated from the following files:
Type3Engine/Button.h
Type3Engine/Button.cpp