T3E::BloodVessel Class Reference
T3E::BloodVessel Class Reference
Public Member Functions
void update (float dTime)
Static Public Member Functions
static void setRange (float range)
AnimatedSprite * getSprite ()
static float getRange ()
Detailed Description
Definition at line 9 of file BloodVessel.h.
Member Function Documentation
static float T3E::BloodVessel::getRange () inline static
Getters
Definition at line 27 of file BloodVessel.h.
Referenced by T3E::Grid::getHexDrawInfo(), T3E::Grid::inRange(), T3E::Grid::moveStemCell(), and setRange().
static void T3E::BloodVessel::setRange (float range) inline static
Setters
Definition at line 21 of file BloodVessel.h.
References getRange().
Referenced by MainGame::run().
The documentation for this class was generated from the following files:
BloodVessel.h
BloodVessel.cpp