MainGame Class Reference
MainGame Class Reference
Public Member Functions
command run (T3E::window *window, T3E::AudioEngine *audioEngine, bool tutorial)
Detailed Description
Definition at line 40 of file MainGame.h.
Member Function Documentation
command MainGame::run (T3E::window * window, T3E::AudioEngine * audioEngine, bool tutorial)
Parameters
[in] Window* The window to render to
[in] AudioEngine* The audio engine to use
[in] Bool flag of weather to run the game with tutorial hints on Run handles initialisation of the state then enters the game loop
Definition at line 33 of file MainGame.cpp.
References T3E::AnimatedSprite::draw(), T3E::Cell::draw(), T3E::ConfigFile::getFloat(), T3E::ConfigFile::getInt(), T3E::ResourceManager::getTexture(), T3E::Cell::ignoreBirthDelay(), T3E::Music::play(), and T3E::BloodVessel::setRange().
The documentation for this class was generated from the following files:
MainGame.h
MainGame.cpp